# **Numpy Creating Arrays**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
import numpy as np
arr=np.array((2,3,4,5))
print(arr)
print(type(arr))

[2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr= np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimensions: ",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


In [ ]:
import numpy as np
arr=np.array([4,32,52,22,5])
print(arr[0])
print(arr[1])

4
32


In [ ]:
arr

array([ 4, 32, 52, 22,  5])

In [ ]:
print(arr[2]+arr[3])

74


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('2nd element from row1: ',arr[0,1])

2nd element from row1:  2


In [ ]:
print(arr[0][1])


2


In [ ]:
print('2nd row 4th element',arr[1,3])

2nd row 4th element 8


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('third element of the second array of the first array:',arr[0,1,2])

third element of the second array of the first array: 6


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Last elemeent from 2nd dim: ",arr[1,-1])

Last elemeent from 2nd dim:  10


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
print(arr[1:5:2])

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
print(arr[0:2,2])

[3 8]


In [ ]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([1, 5, 10], dtype='m8[D]')

print(arr)
print(arr.dtype)

[ 1  5 10]
timedelta64[D]


In [ ]:
import numpy as np

arr = np.array([1, "hello", 3.14, True], dtype='O')

print(arr)
print(arr.dtype)

[1 'hello' 3.14 True]
object


In [ ]:
import numpy as np

arr = np.array(['hello', 'world'], dtype='U')

print(arr)
print(arr.dtype)

['hello' 'world']
<U5


In [ ]:
import numpy as np

# Create a structured data type
# 'i4' is a 4-byte integer, 'f4' is a 4-byte float, 'a10' is a 10-character string
dt = np.dtype([('name', 'S10'), ('age', 'i4'), ('marks', 'f4')])

# Create a structured array
arr = np.array([('Nikhil', 25, 85.5), ('Sonia', 22, 92.0)], dtype=dt)

print(arr)
print(arr.dtype)

[(b'Nikhil', 25, 85.5) (b'Sonia', 22, 92. )]
[('name', 'S10'), ('age', '<i4'), ('marks', '<f4')]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
arr=np.array(["avi","sai","hi"])
print(arr.dtype)

<U3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr=np.array(['a',2,3],dtype='i')
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
arr=np.array([1.3,3.3,5.3])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 3 5]
int32


In [ ]:
arr

array([1.3, 3.3, 5.3])

In [ ]:
new_arr=arr.astype(int)
print(new_arr)
print(new_arr.dtype)


[1 3 5]
int64


In [ ]:
arr=np.array([1,0,3,-7])
new_arr=arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True False  True  True]
bool
