In [1]:
a=10
b=20
if b>a:
  print('b is greater than a')

b is greater than a


In [2]:
x = 10
y = 12
 # if x is greater than y
if x > y:
  print("x > y")
# if x is lesser than y
elif x < y:
  print("x < y")
else:
  print("x = y")

x < y


In [3]:
# Initialize
x = 5

 # True if x is more than 10 or assign False using ternary operator
isGreater = True if x > 10 else False
print(isGreater)

False


In [4]:
numbers=range(1,6)


In [5]:
numbers

range(1, 6)

In [6]:
for i in numbers:
  print(i)

1
2
3
4
5


In [7]:
def addElement(a,b):
  return a+b

In [8]:
result=addElement(2,3)
print(result)

5


In [9]:
emptyList=[]

In [10]:
print(emptyList)


[]


In [11]:
batsmen = ['Rohit', 'Dhawan', 'Kohli', 'Rahane', 'Rayudu', 'Dhoni']


In [12]:
batsmen[0]

'Rohit'

In [13]:
batsmen[1]

'Dhawan'

In [14]:
batsmen[2]

'Kohli'

In [15]:
batsmen[3]

'Rahane'

In [16]:
batsmen[0:2]

['Rohit', 'Dhawan']

In [17]:
batsmen[-1]

'Dhoni'

In [18]:
len(batsmen)

6

In [19]:
batsmen.index('Dhoni')

5

In [20]:
odiDebut = ('Kohli', 2008)


In [21]:
type(odiDebut)

tuple

In [22]:
odiDebut[1]=2009

TypeError: 'tuple' object does not support item assignment

In [23]:
odiDebut2=('sachin',1989)

In [24]:
print(odiDebut+odiDebut2)

('Kohli', 2008, 'sachin', 1989)


In [25]:
setOfNumbers = {6,1,1,2,4,5}


In [26]:
type(setOfNumbers)

set

In [27]:
setOfNumbers

{1, 2, 4, 5, 6}

In [28]:
wcWinners = {
1975:'West Indies',
1979:'West Indies',
1983:'India',
1987:'Australia',
1991:'Pakistan',
1996: 'Sri Lanka',
1999: 'Australia',
2003: 'Australia',
2007: 'Australia',
2011: 'India'
}


In [29]:
import numpy as np


In [30]:
a=np.array([1,2,3,4])

In [31]:
type(a)

numpy.ndarray

In [32]:
a.shape

(4,)

In [33]:
a.size

4

In [34]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [35]:
type(b)

numpy.ndarray

In [36]:
b.shape

(2, 4)

In [37]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
b.size

8

In [39]:
#to get first row elements
b[0]

array([1, 2, 3, 4])

In [40]:
b[0][0]

np.int64(1)

In [41]:
c=b.reshape(4,2)

In [42]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
c.shape

(4, 2)

In [44]:
b.shape

(2, 4)

In [45]:
print(a.sum())
print(a)

10
[1 2 3 4]


In [46]:
a.prod()

np.int64(24)

In [47]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
#to find row elements R1+R2
b.sum(axis=0)

array([ 6,  8, 10, 12])

In [49]:
# to find column wise addition
b.sum(axis=1)

array([10, 26])

In [50]:
# 1. Creating a NumPy array
# NumPy's primary object is the homogeneous multidimensional array.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("1. Created a NumPy array:", a)

# 2. Performing mathematical operations
# You can perform element-wise mathematical operations on arrays.
b = np.array([5, 4, 3, 2, 1])
c = a + b
print("2. Element-wise addition of two arrays:", c)

# 3. Indexing and Slicing
# NumPy offers comprehensive indexing and slicing capabilities.
print("3. First element of the array:", a[0])
print("   Elements from index 1 to 3:", a[1:4])

# 4. Reshaping arrays
# You can change the shape of an array.
d = np.array([[1, 2, 3], [4, 5, 6]])
e = d.reshape(3, 2)
print("4. Reshaped array:\n", e)

# 5. Stacking arrays
# You can stack arrays vertically or horizontally.
f = np.array([7, 8, 9])
g = np.vstack((a,b))
print("5. Vertically stacked arrays:\n", g)

1. Created a NumPy array: [1 2 3 4 5]
2. Element-wise addition of two arrays: [6 6 6 6 6]
3. First element of the array: 1
   Elements from index 1 to 3: [2 3 4]
4. Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
5. Vertically stacked arrays:
 [[1 2 3 4 5]
 [5 4 3 2 1]]


In [51]:
import numpy as np

# Create a 3x3 array
array_a = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create a 1D array (or a scalar)
scalar_b = 10

# Add the scalar to the array. NumPy broadcasts the scalar to each element.
result_array = array_a + scalar_b

print("Original Array:\n", array_a)
print("\nScalar to add:", scalar_b)
print("\nResult after broadcasting:\n", result_array)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Scalar to add: 10

Result after broadcasting:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
